# Generated by Django 2.0 on 2018-05-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
